spring:
  application:
    name: analyze

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.sks.precheck.analyze.domain
  configuration:
    map-underscore-to-camel-case: true