[dlprem01-테스트개발][DISK_HOME][수치][<][90][20]
[dlprem01-테스트개발][PROC_COUNT][수치][>][20][10]
[dlprem01-테스트개발][PUSH_STATUS][문구][실패,오류,Fail]
[dlprem01-테스트개발][DATE_BDAY][날짜]
[dlprem01-테스트개발][MEM_MBSOSI][존재]
[dlprem01-테스트개발][STOPLOSS_CNT][정보]

[orderserver-자동주문][DISK_HOME][수치][<][95][10]
[orderserver-자동주문][PROC_COUNT][수치][>][30][10]
